### ISSUE TITLE
Intégration de Stripe.io ?

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2016#1]
Paymill : https://www.paymill.com/fr/tarification prend 2.95% + 0.28€ par transaction 
Yurplan prend 2% ou 0,49€ 

Donc pour nous l'impact : 

* Billet 2 J : 70€
  * Paymill : 2,35€ / 1 Place | 2,09€ si 10 places de prises
  * Yurplan : 1,40€
* Billet 1 J : 40€
  * Paymill : 1,46€ / 1 Place | 1,21€ si 10 places de prises
  * Yurplan : 0,80€
* Tarif Réduit : 10€
  * Paymill : 0,58€ / 1 Place | 0,32€ si 10 places de prises
  * Yurplan : 0,49€

Au niveau du prix c'est pas hyper intéressant reste à voir si on veut d'autre choses dessus ?

**Comment by jlandure** [comment]
aucun intérêt. Soit on utilise stripe.io soit on utilise yurplan

**Comment by jefBinomed** [comment]
Donc pour nous l'impact :

* Billet 2 J : 70€
 * Stripe.io : 1,23€
 * Yurplan : 1,40€
* Billet 1 J : 40€
 * Stripe.io : 0.81€
 * Yurplan : 0,80€
* Tarif Réduit : 10€
 * Stripe.io : 0,39€
 * Yurplan : 0,49€

C'est du coup en effet plus intéressant

**Comment by jlandure** [comment]
cf https://docs.google.com/spreadsheets/d/1ljiq1NOGTgUaMccT8Ainu5T-YnqC3g1ygvSfVAUaKRo/edit#gid=0
Tu as mis à jour le doc @jefBinomed ?

**Comment by jlandure** [comment]
Pour info, j'ai validé un compte sur stripe.io sur notre compte GDG. On va pouvoir tester le paiement en ligne ;)

**Comment by jefBinomed** [comment]
Non j'ai pas mis à jour le doc mais je le fais là, du coup, va falloir qu'on assure si on intègre nous même la solution :p :)

**Comment by jefBinomed** [comment]
Mis à jour et je sais pas comment j'ai fait, je devais être fatigué quand j'ai fait mes calculs ! Stripe.io nous coûte plus cher au final 877€ contre 809€ pour Yurplan

**Comment by jlandure** [comment]
ok donc on abandonne 👎
