### ISSUE TITLE
Gros Gros problèmes d'affichages 

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2016#107]
Il semblerait que l'ajout de la div de favoris casse un peu tout sur la page principale....

Capture FF sous Linux

![site_pb_ff](https://cloud.githubusercontent.com/assets/681267/18541373/29b34cb2-7b25-11e6-8448-c607269773cb.png)

Capture Chrome sous Linux

![site_pb_chrome](https://cloud.githubusercontent.com/assets/681267/18541434/80531bb0-7b25-11e6-8495-8aff11f402a1.png)

J'ai le soucis aussi bien en dev que sur la branche déployée et j'ai aussi le problème en prod (mais uniquement sur chrome)

**Comment by jefBinomed** [comment]
Après un peu d'inspection devtools, il semblerait que le pb vienne de la vidéo, si je met en display none la partie avec la vidéo, le site s'affiche à nouveau correctement

**Comment by jefBinomed** [comment]
Le bug sous firefox est un autre, je vais crééer une autre issue

**Comment by jlandure** [comment]
Ahh les codecs sont différents entre linux / windows / mac peut-être ?
Ton bug jef ressemble au bug de Sebastien envoyé par email...

**Comment by jefBinomed** [comment]
ué je sais sauf que au dela des codecs, si je scroll, ça cache litéralement le site et puis le pire c'est que la vidéo s'affiche bien, donc non, je penses qu'il y a un soucis autre

**Comment by jlandure** [comment]
t'es en quelle résolution ? 1920 ?

**Comment by jefBinomed** [comment]
uep mais avec les devtools d'ouvert, en changeant de résolution, le pb persiste

**Comment by jlandure** [comment]
je reproduis sur mon mac en 1920 ;)

**Comment by jlandure** [comment]
c'est le z-index le problème 👍

**Comment by jefBinomed** [comment]
c'était pas déjà lié à une correction de @pguyard sur la vidéo ?

**Comment by jlandure** [comment]
nop j'ai presque fini la correction mais en réunion. 👎

**Comment by jlandure** [comment]
tu testera @jefBinomed ? c'est en prod direct ! (/mode ouf on) https://devfest.gdgnantes.com/

**Comment by pguyard** [comment]
on peut clore non ?

**Comment by jefBinomed** [comment]
duplicate #108
