### ISSUE TITLE
Probleme d'affichage de la timeline sur l'agenda

### ISSUE THREAD

**Issue by Nebulis** [GDG-Nantes/devFestSite-2016#131]
Hello,

La timeline ne s'affiche pas correctement sur mon poste : 
![image](https://cloud.githubusercontent.com/assets/503185/19645462/1ffee76e-99f5-11e6-9c3b-77ac9f3d0b93.png)

Pour corriger le problème, on peut remplacer la propriété `height : 100%` par `flex-grow: 1` sur la classe *devfest-agenda2-hour-line*

**Comment by pguyard** [comment]
@Nebulis : merci ; la prochaine fois hésite pas à faire une PR ;)
