### ISSUE TITLE
ctrl+clic do not work on agenda

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#138]
cf https://twitter.com/ThainBBdL/status/792673271170867200

```
 Est ce que vous pouvez changer les div onclick=loc.href par des a sur la page agenda svp?On peut pas ouvrir en onglet sinon:/
```

**Comment by pguyard** [comment]
euh personne ne s'est plaint de ça sinon... moi ça marche bien sur téléphone et pc. 
Sinon une balise a href avec plein de div dedans c'est pas top non ?

**Comment by jlandure** [comment]
Heuu je comprend pas trop @pguyard 
Je dis: 
1/ sur twitter, qq'un s'est plaint
2/ effectivement le ctrl-clic n'ouvre pas un nouvel onglet
3/ balise a avec des div dessous, ça me choque pas perso...
