### ISSUE TITLE
Agenda cassé ?

### ISSUE THREAD

**Issue by olaurendeau** [GDG-Nantes/devFestSite-2016#140]
<img width="518" alt="capture d ecran 2016-11-01 a 19 12 07" src="https://cloud.githubusercontent.com/assets/1516110/19901353/225dff4a-a067-11e6-9426-3007779450dd.png">

**Comment by pguyard** [comment]
un problème de CSS non chargée ? je ne reproduit pas...

**Comment by olaurendeau** [comment]
Ah oui sans doute. En wipant le cache c'est revenu à la normal, désolé !

**Comment by jlandure** [comment]
cf 4805bfb93f22ae90889c18f7f7575adea8743388
