### ISSUE TITLE
Map Indoor

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#18]
S'inspirer de https://github.com/codrops/Interactive3DMallMap

**Comment by pguyard** [comment]
à faire pour le badge ?

**Comment by jefBinomed** [comment]
je suis de l'avis de @pguyard vaut mieux mettre ça dans le badge

**Comment by jefBinomed** [comment]
on peut ajouter la photo du badge dans la pratique ça peut être cool
