### ISSUE TITLE
Uniformiser la taille des logos des sponsors par pack

### ISSUE THREAD

**Issue by pguyard** [GDG-Nantes/devFestSite-2016#19]

**Comment by pguyard** [comment]
le logo sopra parait 3x plus grand que le logo sqli on laisse comme ça ?

**Comment by jefBinomed** [comment]
bah en fait, c'est pas de notre faute si leur logo est fin :( il fait la même largeur et j'avoue que je vois pas trop ce qu'on peut y faire ? Ou alors faut les contacter pour leur demander un logo moins plat ?
