### ISSUE TITLE
A quoi s'attendre / Uniformiser les 3 colonnes

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#20]
<img width="1111" alt="capture d ecran 2016-05-10 a 13 36 49" src="https://cloud.githubusercontent.com/assets/525974/15145209/9629310c-16b4-11e6-92c5-caf7b887ea86.png">

* Le premier logo est plus gros que les autre
* Faire un détour pour bien identifier les 3 logos (1 rond bleu, 1 rond rouge, 1 rond vert ?)
* Uniformiser le texte pour qu'il soit de la même taille...

**Comment by pguyard** [comment]
c'est encore plus moche en mobile
