### ISSUE TITLE
Nombres / Ajouter de l'espace

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#21]
<img width="865" alt="capture d ecran 2016-05-10 a 13 40 48" src="https://cloud.githubusercontent.com/assets/525974/15145266/dce9c566-16b4-11e6-8cf8-d97d09133a29.png">

Prévoir d'ajouter du padding + espacer le texte...
Rendre ça responsive 👍

**Comment by jefBinomed** [comment]
sur les résolutions classiques, le pb n'est plus présent
