### ISSUE TITLE
Pratique - Code promo Hotel

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#25]
Est-ce normal d'avoir écrit:
```
Situé juste en face de la Cité des Congrès, le Residhome les Berges de la Loire vous propose des tarifs négociés avec le code « DEVFEST 2015 ».
```
cf https://v3-dot-devfestnantes2016.appspot.com/pratique.html

**Comment by pguyard** [comment]
Même les contacts sont ceux de l'an passé. On les a recontacter cette année ?
