### ISSUE TITLE
Team - Ajouter comme l'an passé les liens réseaux sociaux ?

### ISSUE THREAD

**Issue by pguyard** [GDG-Nantes/devFestSite-2016#34]

**Comment by jlandure** [comment]
Ils sont présents en bas de page.

Le jeu. 12 mai 2016 00:25, Pierrick Guyard <notifications@github.com> a
écrit :

**Comment by pguyard** [comment]
pas ceux du gdg mais de chacun d'entre nous ? c'est peut être pas utile ? as you want

**Comment by jlandure** [comment]
Ok j'avais pas compris. Perso je trouve ça bien... LinkedIn / twitter
suffisant pour moi. :)

Le jeu. 12 mai 2016 08:41, Pierrick Guyard <notifications@github.com> a
écrit :

**Comment by pguyard** [comment]
J'ai ajouté en commentaire les infos de l'année dernière ; RAF linkedin demandé par Julien + Mettre en forme ces données

**Comment by jefBinomed** [comment]
En fait en prod ça marche pas, les liens et les svg sont bien présents mais y a un truc qui manque, du coup, ça s'affiche pas

**Comment by jlandure** [comment]
effectivement c'est KO :(

**Comment by pguyard** [comment]
problème de style et de css je pense @bpetetot une idée ?
