### ISSUE TITLE
Presse - préparer la page ou la cacher pour la mep

### ISSUE THREAD

**Issue by pguyard** [GDG-Nantes/devFestSite-2016#35]
https://v3-dot-devfestnantes2016.appspot.com/presse.html

Faut-il l'ajouter dans dans le menu ?

1ers liens :
- http://www.groupe-creative.fr/creative-sinvestit-dans-la-vie-locale-nantaise/

**Comment by bpetetot** [comment]
On va attendre d'avoir plus d'éléments pour ajouter la page

**Comment by pguyard** [comment]
ok il faut virer le lien du footer alors non ?

**Comment by bpetetot** [comment]
Bien vu ! Je l'avais oublié celui là :P
