### ISSUE TITLE
Problème de scrollbar sur la map

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2016#36]
Quand on est sur la page d'accueil au moment on la souris se trouve à la même hauteur que la map, il y a une seconde scrollbar qui apparait

**Comment by jefBinomed** [comment]
j'ai même le problème dès le début de la page, si je bouge mon curseur de souris au milieu ça me fait apparaître la scroll bar, comme une sorte de super div qui devient trop grande....

**Comment by bpetetot** [comment]
Je n'arrive pas à reproduire sur chrome avec mon mac...

**Comment by jefBinomed** [comment]
Je vais m'en occuper alors

Le mar. 24 mai 2016 à 23:16, bpetetot <notifications@github.com> a écrit :

> Je n'arrive pas à reproduire sur chrome avec mon mac...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GDG-Nantes/devFestSite-2016/issues/36#issuecomment-221396403>
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau

**Comment by jefBinomed** [comment]
C'est un problème graphique lié à des extensions installées sur mon chrome. Je clos
