### ISSUE TITLE
Infos à mettre à jour dans les tickets

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2016#37]
On précise dans la partie tickets que les pass 1 journée ont accès à l'after. Il faudrait mieux préciser les choses sur l'after dans la FAQ car je voyais bien un truc du genre : pass 2J et pass mercredi ont accès à l'after. Les pass jeudis n'ont pas accès à l'after

**Comment by jlandure** [comment]
Faut surtout ne pas oublier une mention sur le droit à l'image. _pareil pour les speakers_
