### ISSUE TITLE
Remettre le drapeau pour accéder à la version anglaise ?

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2016#38]
J'ai vu qu'on a un texte et plus un icone pour indiquer qu'on veut changer de langue. Est ce qu'on revient sur la version précédente ?

**Comment by pguyard** [comment]
as you want par contre la page https://v3-dot-devfestnantes2016.appspot.com/en ne marche pas

**Comment by bpetetot** [comment]
ouai mais par contre quand on pointe la page ça fonctionne : https://v3-dot-devfestnantes2016.appspot.com/en/index.html

**Comment by jlandure** [comment]
Faut modifier le app.yaml 👌
