### ISSUE TITLE
Uniformisation des liens dans la page /pratique.html au niveau du tramway

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2016#39]
On met un lien vers l'arrêt de tram de la ligne 1 alors qu'on met pas de lien pour la ligne 4. Il faudrait qu'on soit cohérent et qu'on choisisse un truc qui soit pareil pour les 2. Perso, je trouve que le lien n'apporte pas grand chose et je serais d'avis de le virer...

**Comment by pguyard** [comment]
bah sur maps y'a pas la ligne 4 donc c'est pas possible de faire un lien moi je laisserai comme ça
