### ISSUE TITLE
Diminuer le padding dans les blocs en mode mobile

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2016#41]
Il y a trop d'espace de perdu sur mobile dans les blocs de données : On pourrait baisser la padding. 

Voici un imprime écran en mode emulation sur un S5
![padding_bug](https://cloud.githubusercontent.com/assets/681267/15509706/b56f2302-21d4-11e6-949a-0bf89afa4a63.png)

**Comment by jefBinomed** [comment]
faudrait faire la même chose sur la page d'accueil au niveau des prixs
![bug_padding_2](https://cloud.githubusercontent.com/assets/681267/15509939/a7105852-21d5-11e6-96ac-4005c848738e.png)

**Comment by bpetetot** [comment]
fermer par le commit #7b238255354187e4dabe14a51fdffbed1e1467a7
