### ISSUE TITLE
[PageSpeed] Redimensionner les images

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#55]
* sponsors/conserto.png est redimensionné en code HTML ou CSS de 1024 x 299 à 200 x 58. Afficher une image mise à l'échelle pourrait libérer 64.2 Ko (réduction de 96%).
* sponsors/externatic.png est redimensionné en code HTML ou CSS de 1432 x 733 à 120 x 60. Afficher une image mise à l'échelle pourrait libérer 57.2 Ko (réduction de 99%).
* sponsors/figaro.jpg est redimensionné en code HTML ou CSS de 600 x 150 à 100 x 25. Afficher une image mise à l'échelle pourrait libérer 53.6 Ko (réduction de 97%).
* lego/lego_happy.png est redimensionné en code HTML ou CSS de 342 x 342 à 200 x 200. Afficher une image mise à l'échelle pourrait libérer 53.1 Ko (réduction de 65%).
* sponsors/open.png est redimensionné en code HTML ou CSS de 694 x 243 à 180 x 63. Afficher une image mise à l'échelle pourrait libérer 47.7 Ko (réduction de 93%).
* lego/lego_computer.png est redimensionné en code HTML ou CSS de 342 x 342 à 200 x 200. Afficher une image mise à l'échelle pourrait libérer 41.5 Ko (réduction de 65%).
* sponsors/asi.png est redimensionné en code HTML ou CSS de 400 x 175 à 120 x 53. Afficher une image mise à l'échelle pourrait libérer 37.8 Ko (réduction de 90%).
* sponsors/sopra.png est redimensionné en code HTML ou CSS de 888 x 113 à 200 x 25. Afficher une image mise à l'échelle pourrait libérer 37.3 Ko (réduction de 95%).
* sponsors/nantestech.png est redimensionné en code HTML ou CSS de 400 x 297 à 100 x 40. Afficher une image mise à l'échelle pourrait libérer 31.4 Ko (réduction de 96%).
* sponsors/lafourchette.png est redimensionné en code HTML ou CSS de 1559 x 409 à 120 x 31. Afficher une image mise à l'échelle pourrait libérer 31.2 Ko (réduction de 99%).
* sponsors/edoceo.png est redimensionné en code HTML ou CSS de 785 x 192 à 180 x 44. Afficher une image mise à l'échelle pourrait libérer 28.5 Ko (réduction de 94%).
* lego/brick_simple_green.png est redimensionné en code HTML ou CSS de 217 x 180 à 48 x 40. Afficher une image mise à l'échelle pourrait libérer 27.7 Ko (réduction de 95%).
* sponsors/sqli.png est redimensionné en code HTML ou CSS de 1513 x 711 à 200 x 94. Afficher une image mise à l'échelle pourrait libérer 27.6 Ko (réduction de 98%).
* lego/brick_simple_yellow.png est redimensionné en code HTML ou CSS de 217 x 180 à 48 x 40. Afficher une image mise à l'échelle pourrait libérer 27.0 Ko (réduction de 95%).
* sponsors/github.png est redimensionné en code HTML ou CSS de 2000 x 665 à 180 x 60. Afficher une image mise à l'échelle pourrait libérer 25.2 Ko (réduction de 99%).
* sponsors/zenika.png est redimensionné en code HTML ou CSS de 959 x 575 à 200 x 100. Afficher une image mise à l'échelle pourrait libérer 25.0 Ko (réduction de 96%).
* lego/brick_simple_red.png est redimensionné en code HTML ou CSS de 217 x 180 à 48 x 40. Afficher une image mise à l'échelle pourrait libérer 24.7 Ko (réduction de 95%).
* lego/brick_simple_blue.png est redimensionné en code HTML ou CSS de 217 x 180 à 48 x 40. Afficher une image mise à l'échelle pourrait libérer 24.3 Ko (réduction de 95%).
* sponsors/cap.png est redimensionné en code HTML ou CSS de 389 x 90 à 180 x 42. Afficher une image mise à l'échelle pourrait libérer 22.8 Ko (réduction de 78%).
* sponsors/softeam.png est redimensionné en code HTML ou CSS de 1850 x 600 à 120 x 39. Afficher une image mise à l'échelle pourrait libérer 22.2 Ko (réduction de 99%).
* sponsors/catamania.png est redimensionné en code HTML ou CSS de 317 x 100 à 120 x 38. Afficher une image mise à l'échelle pourrait libérer 21.5 Ko (réduction de 85%).
* sponsors/google.png est redimensionné en code HTML ou CSS de 1158 x 385 à 200 x 66. Afficher une image mise à l'échelle pourrait libérer 20.8 Ko (réduction de 97%).
* sponsors/gfi.png est redimensionné en code HTML ou CSS de 300 x 211 à 120 x 60. Afficher une image mise à l'échelle pourrait libérer 18.5 Ko (réduction de 88%).
* sponsors/creative.png est redimensionné en code HTML ou CSS de 415 x 100 à 200 x 48. Afficher une image mise à l'échelle pourrait libérer 18.1 Ko (réduction de 76%).
* sponsors/neosoft.png est redimensionné en code HTML ou CSS de 480 x 149 à 200 x 62. Afficher une image mise à l'échelle pourrait libérer 15.9 Ko (réduction de 82%).
* sponsors/beemoov.png est redimensionné en code HTML ou CSS de 336 x 100 à 120 x 36. Afficher une image mise à l'échelle pourrait libérer 12.9 Ko (réduction de 87%).
* sponsors/onepoint.png est redimensionné en code HTML ou CSS de 2560 x 780 à 120 x 37. Afficher une image mise à l'échelle pourrait libérer 12.1 Ko (réduction de 99%).
* sponsors/apside.png est redimensionné en code HTML ou CSS de 1528 x 434 à 120 x 34. Afficher une image mise à l'échelle pourrait libérer 10.3 Ko (réduction de 99%).
* sponsors/netapsys.png est redimensionné en code HTML ou CSS de 292 x 100 à 180 x 62. Afficher une image mise à l'échelle pourrait libérer 10.0 Ko (réduction de 61%).
* lego/lego_geek.jpg est redimensionné en code HTML ou CSS de 342 x 342 à 200 x 200. Afficher une image mise à l'échelle pourrait libérer 9.1 Ko (réduction de 65%).
* sponsors/sii.png est redimensionné en code HTML ou CSS de 200 x 139 à 180 x 90. Afficher une image mise à l'échelle pourrait libérer 6.1 Ko (réduction de 42%).
* sponsors/mstream.png est redimensionné en code HTML ou CSS de 332 x 67 à 100 x 20. Afficher une image mise à l'échelle pourrait libérer 5.9 Ko (réduction de 91%).
* sponsors/epitech.png est redimensionné en code HTML ou CSS de 247 x 90 à 200 x 73. Afficher une image mise à l'échelle pourrait libérer 5.7 Ko (réduction de 35%).
* sponsors/accenture.png est redimensionné en code HTML ou CSS de 244 x 100 à 180 x 74. Afficher une image mise à l'échelle pourrait libérer 5.0 Ko (réduction de 46%).
* sponsors/residhome.png est redimensionné en code HTML ou CSS de 143 x 91 à 100 x 40. Afficher une image mise à l'échelle pourrait libérer 3.8 Ko (réduction de 69%).
* sponsors/sogeti.png est redimensionné en code HTML ou CSS de 300 x 68 à 120 x 27. Afficher une image mise à l'échelle pourrait libérer 2.1 Ko (réduction de 84%).
* sponsors/seyos.png est redimensionné en code HTML ou CSS de 178 x 70 à 120 x 47. Afficher une image mise à l'échelle pourrait libérer 1.9 Ko (réduction de 54%).

**Comment by jlandure** [comment]
Les images représentent 75% de la taille du site téléchargé.

**Comment by jlandure** [comment]
Je viens de refaire le pagespeed. Apparemment il en reste encore à changer de taille (une dizaine).

**Comment by jefBinomed** [comment]
moi aussi, je viens de le relancer et j'ai plus qu'une image, une google maps qu'on maitrise pas

**Comment by jefBinomed** [comment]
tu peux relancer stp ?

**Comment by jlandure** [comment]
bah j'ai toujours des soucis:
* images/lego/lego_happy.png est redimensionné en code HTML ou CSS de 342 x 342 à 200 x 200. Afficher une image mise à l'échelle pourrait libérer 53.1 Ko (réduction de 65%).
* images/lego/lego_computer.png est redimensionné en code HTML ou CSS de 342 x 342 à 200 x 200. Afficher une image mise à l'échelle pourrait libérer 41.5 Ko (réduction de 65%).
* images/sponsors/netapsys.png est redimensionné en code HTML ou CSS de 292 x 100 à 180 x 62. Afficher une image mise à l'échelle pourrait libérer 10.0 Ko (réduction de 61%).
* images/lego/lego_geek.jpg est redimensionné en code HTML ou CSS de 342 x 342 à 200 x 200. Afficher une image mise à l'échelle pourrait libérer 9.1 Ko (réduction de 65%).
* images/sponsors/sii.png est redimensionné en code HTML ou CSS de 200 x 139 à 180 x 90. Afficher une image mise à l'échelle pourrait libérer 6.1 Ko (réduction de 42%).
* images/sponsors/epitech.png est redimensionné en code HTML ou CSS de 247 x 90 à 200 x 73. Afficher une image mise à l'échelle pourrait libérer 5.7 Ko (réduction de 35%).
* images/sponsors/accenture.png est redimensionné en code HTML ou CSS de 244 x 100 à 180 x 74. Afficher une image mise à l'échelle pourrait libérer 5.0 Ko (réduction de 46%).
* images/sponsors/residhome.png est redimensionné en code HTML ou CSS de 143 x 91 à 100 x 40. Afficher une image mise à l'échelle pourrait libérer 3.8 Ko (réduction de 69%).

**Comment by jlandure** [comment]
Page team:
* images/2015/benevoles.png est redimensionné en code HTML ou CSS de 2048 x 923 à 699 x 315. Afficher une image mise à l'échelle pourrait libérer 1.8 Mo (réduction de 88%).

**Comment by jlandure** [comment]
LGTM

**Comment by jlandure** [comment]
J'ai l'impression que certains logos de sponsors sont devenus moches:
cf le ratio de github ou edoceo ou encore Google...

**Comment by jefBinomed** [comment]
C'est en récupérant les contenus optimisé par pagespeed..
