### ISSUE TITLE
Supprimer l'appel à main.js

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#56]
`index.html` a un ` <script src="/scripts/main.js"></script>` 
Or ce fichier n'est pas trouvé
```
Request URL:https://v3-dot-devfestnantes2016.appspot.com/scripts/main.js
Request Method:GET
Status Code:404 
```

Il s'appelle `main.min.js` dans `dist`

**Comment by jefBinomed** [comment]
c'est résolu non ? je vois plus d'erreur dans la console
