### ISSUE TITLE
Ajouter un autre logo pour le menu

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#65]
Quand on ouvre le menu, le logo en haut à gauche est très petit par rapport à la place que l'on a.
Faudrait voir pour:
1/ soit ajouter un logo DevFest plus gros
2/ soit garder le logo actuel et mettre DevFest by GDG Nantes et remettre le logo GDG Nantes

**Comment by bpetetot** [comment]
Ou on peut ajouter la date et le lieu en plus du logo.

Sinon vous avez été fort au niveau de l'optimisation des images, le logo est tout flou maintenant...

**Comment by jlandure** [comment]
lol @bpetetot je trouvais ça un peu flou effectivement.
