### ISSUE TITLE
Enlever le sourcemap pour la prod

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#76]
Ça fait des appels pour rien et des erreurs dans la console AppEngine pour rien 👍

**Comment by pguyard** [comment]
If you load a page without dev tools opened, there is no http request for source maps.
The behaviour was the same in Chrome 43 and Firefox 38.
So it appears they would be no impact on production environment.

**Comment by jlandure** [comment]
ok je savais pas !
