### ISSUE TITLE
Ajouter une partie Presse avec les affiches

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#84]

**Comment by pguyard** [comment]
RAF : 
1. revoir la présentation du kit média + ajouter les logos
2. a voir si on ajoute un laïus pour obtenir une accréditation presse ? 
3. ajouter la section il parle de nous :
  - http://www.tasvu.fr/nantes/devfest-nantes-2016/
  - http://www.lacite-nantes.fr/fr/r5_assister/530_detail.php?evenement=2_26705
  - http://www.saloonapp.co/conferences/3c4a939a-5f36-48b5-bdfc-ec90a71f0641
  - https://www.evensi.fr/devfest-nantes-2016-la-cite-le-centre-des-congres-de-nantes/179703294
  - https://etrigg.com/event/devfest-nantes-2016/22131251/
  - http://organic-orchestra.com/agenda/conference-b-glove-devfest-nantes/
  - https://www.koikonfait.com/event/5758826b2e89ceb34c1eeb9a/devfest-nantes-2016
  - http://lanyrd.com/2016/devfestnantes/
  - http://allevents.in/nantes/devfest-nantes-2016/610288295813024

**Comment by jefBinomed** [comment]
Le laïus pour la presse, je suis pas forcément convaincu....

Par contre peut être que je rajouterais un ptit texte avec le kit media, un truc bateau du genre à afficher partout mais en mieux :p

**Comment by jlandure** [comment]
Avoir un kit media ça serait cool.
=> LGTM
