### ISSUE TITLE
Le burger menu est tout le temps présent

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2016#9]
Il fait doublon avec le menu classique, il faut gérer le fait que le burger menu n'apparaisse que sur mobile

**Comment by bpetetot** [comment]
C'est comme ça dans material design lite et apparement dans les guidelines material design... 
Si on veut empêcher ça, il faut modifier les scripts de la librarie.
Je propose qu'on le laisse :)
