### ISSUE TITLE
Le champ "Autres urls (Blog, Linkedin,...)" du cfp n'est pas restitué dans les pages speakers

### ISSUE THREAD

**Issue by pguyard** [GDG-Nantes/devFestSite-2016#94]

**Comment by bpetetot** [comment]
Je n'ai pas géré l'affichage des url blog et linkedin...

Ca serait à ajouter dans le composant : 
devFestSite-2016/app/scripts/components/social-chip.js

Et bien sûr ajouter ensuite dans le fichier devfest.json le social link correspondant

**Comment by pguyard** [comment]
k je vais regarder ça

**Comment by pguyard** [comment]
raf json
