### ISSUE TITLE
Corrections sur le talk de design sprint

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2016#96]
Voici les remarque du speaker

>Bonjour, pouvez-vous ajouter l'adresse de mon blog dans la description s'il vous plait ? >http://www.design-en-entreprise.fr/ Merci

>Bonjour, j'aurais besoin de corriger une faute d'orthographe dans la description : "Venez découvrir ce qui fait le succès des Google Design Sprint !". Il faut ajouter un S à sprint. Merci

**Comment by pguyard** [comment]
Ou doit-on ajouter l'url du blog ?

**Comment by bpetetot** [comment]
Je n'ai pas géré l'affichage des url blog et linkedin...

Ca serait à ajouter dans le composant : 
devFestSite-2016/app/scripts/components/social-chip.js

Et bien sûr ajouter ensuite dans le fichier devfest.json le social link correspondant

**Comment by bpetetot** [comment]
A faire évoluer dans l'issue #94
