### ISSUE TITLE
Impossible de sélectionner du texte comme le titre d'un talk

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2016#97]
Que ce soit dans la page `agenda` ou la page `session.html`
Dès qu'on sélectionne du texte, ça change de page ou reload la page...
A la limite sur la page `agenda` ok mais sur la page `session` c'est moyen...

**Comment by bpetetot** [comment]
sur la page `session` le texte est maintenant sélectionnable
corrigé ici : 64febda6e3fb1053706c76c78947c055cee541da
